Rechunk and update readme.md

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,6 +11,11 @@ on:
     paths-ignore:
       - '**/README.md'
   workflow_dispatch:
+    inputs:
+      fresh-rechunk:
+        description: 'Clear rechunk history'
+        type: boolean
+        default: false
 
 env:
   IMAGE_DESC: "Filotimo Linux OCI Image"
@@ -43,6 +48,76 @@ jobs:
 
       - name: Maximize build space
         uses: ublue-os/remove-unwanted-software@v7
+
+      - name: Matrix Variables
+        run: |
+          if [ "${{ matrix.image_flavor }}" = "nvidia" ]; then
+            echo "IMAGE_NAME=${{ github.event.repository.name }}-${{ matrix.image_flavor }}" >> $GITHUB_ENV
+          elif [ "${{ matrix.image_flavor }}" = "main" ]; then
+            echo "IMAGE_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
+          fi
+
+      - name: Get Current Fedora Version
+        id: labels
+        shell: bash
+        run: |
+          set -eo pipefail
+          ver=$(skopeo inspect docker://ghcr.io/ublue-os/kinoite-main:${{ env.MAJOR_VERSION }} | jq -r '.Labels["org.opencontainers.image.version"]')
+          if [ -z "$ver" ] || [ "null" = "$ver" ]; then
+            echo "inspected image version must not be empty or null"
+            exit 1
+          fi
+          echo "VERSION=$ver" >> $GITHUB_OUTPUT
+
+      - name: Check just syntax
+        uses: ublue-os/just-action@v2
+
+      # Build metadata
+      - name: Image Metadata
+        uses: docker/metadata-action@v5
+        id: meta
+        with:
+          images: |
+            ${{ env.IMAGE_NAME }}
+
+          labels: |
+            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
+            org.opencontainers.image.version=${{ steps.labels.outputs.VERSION }}
+            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
+            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
+
+      - name: Pull main, akmods, rechunk images
+        uses: Wandalen/wretry.action@v3.5.0
+        with:
+          attempt_limit: 3
+          attempt_delay: 15000
+          command: |
+            # pull the base images used for FROM in Containerfile so
+            # we can retry on that unfortunately common failure case
+            sudo podman pull docker://ghcr.io/ublue-os/kinoite-main:${{ env.MAJOR_VERSION }}
+            sudo podman pull docker://ghcr.io/ublue-os/akmods:fsync-${{ env.MAJOR_VERSION }}
+            sudo podman pull docker://ghcr.io/ublue-os/akmods-extra:fsync-${{ env.MAJOR_VERSION }}
+
+            # Add rechunk as well to remove this source of failure
+            sudo podman pull ghcr.io/hhd-dev/rechunk:v0.8.3
+
+      - name: Build Image
+        id: build_image
+        run: |
+          sudo buildah build \
+            --build-arg IMAGE_NAME=${{ env.IMAGE_NAME }} \
+            --build-arg IMAGE_TAG=${{ env.IMAGE_TAG }} \
+            --build-arg FEDORA_MAJOR_VERSION=${{ env.MAJOR_VERSION }} \
+            --build-arg TIMESTAMP_TAG=${{ env.TIMESTAMP_TAG }} \
+            --target ${{ env.IMAGE_NAME }} \
+            --tag raw-img .
+
+      - name: Remove auxiliary images
+        # We are tight on space, need at least 2x for OSTree
+        run: |
+          sudo podman image rm docker://ghcr.io/ublue-os/kinoite-main:${{ env.MAJOR_VERSION }}
+          sudo podman image rm docker://ghcr.io/ublue-os/akmods:fsync-${{ env.MAJOR_VERSION }}
+          sudo podman image rm docker://ghcr.io/ublue-os/akmods-extra:fsync-${{ env.MAJOR_VERSION }}
 
       - name: Generate tags
         id: generate-tags
@@ -85,61 +160,46 @@ jobs:
           echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT
           echo "TIMESTAMP_TAG=$TIMESTAMP" >> $GITHUB_ENV
 
-      - name: Matrix Variables
-        run: |
-          if [ "${{ matrix.image_flavor }}" = "nvidia" ]; then
-            echo "IMAGE_NAME=${{ github.event.repository.name }}-${{ matrix.image_flavor }}" >> $GITHUB_ENV
-          elif [ "${{ matrix.image_flavor }}" = "main" ]; then
-            echo "IMAGE_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
-          fi
-
-      - name: Get Current Fedora Version
-        id: labels
+       # Generate the previous image reference used by the Rechunker
+      - name: Generate previous reference
+        id: generate-prev-ref
         shell: bash
         run: |
-          set -eo pipefail
-          ver=$(skopeo inspect docker://ghcr.io/ublue-os/kinoite-main:${{ env.MAJOR_VERSION }} | jq -r '.Labels["org.opencontainers.image.version"]')
-          if [ -z "$ver" ] || [ "null" = "$ver" ]; then
-            echo "inspected image version must not be empty or null"
-            exit 1
+          if [ "${{ github.event.inputs.fresh-rechunk }}" == "true" ]; then
+            IMAGEREF=""
+          else
+            IMAGEREF="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
           fi
-          echo "VERSION=$ver" >> $GITHUB_OUTPUT
 
-      # Build metadata
-      - name: Image Metadata
-        uses: docker/metadata-action@v5
-        id: meta
+          echo "ref=${IMAGEREF}" >> $GITHUB_OUTPUT
+
+          echo "Generated the following:"
+          cat $GITHUB_OUTPUT
+
+      # Reprocess raw-img using rechunker which will delete it
+      - name: Run Rechunker
+        id: rechunk
+        uses: hhd-dev/rechunk@v0.8.6
         with:
-          images: |
-            ${{ env.IMAGE_NAME }}
-
+          rechunk: 'ghcr.io/hhd-dev/rechunk:v0.8.3'
+          ref: 'raw-img'
+          prev-ref: '${{ steps.generate-prev-ref.outputs.ref }}'
+          version: '${{ env.TIMESTAMP_TAG }}'
           labels: |
             io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
             org.opencontainers.image.version=${{ steps.labels.outputs.VERSION }}
             org.opencontainers.image.description=${{ env.IMAGE_DESC }}
             org.opencontainers.image.title=${{ env.IMAGE_NAME }}
 
-      # Build image using Buildah action
-      - name: Build Image
-        id: build_image
-        uses: redhat-actions/buildah-build@v2
-        with:
-          containerfiles: |
-            ./Containerfile
-          # Postfix image name with -custom to make it a little more descriptive
-          # Syntax: https://docs.github.com/en/actions/learn-github-actions/expressions#format
-          image: ${{ env.IMAGE_NAME }}
-          tags: |
-            ${{ steps.generate-tags.outputs.alias_tags }}
-          build-args: |
-            IMAGE_NAME=${{ env.IMAGE_NAME }}
-            IMAGE_TAG=${{ env.IMAGE_TAG }}
-            FEDORA_MAJOR_VERSION=${{ env.MAJOR_VERSION }}
-            TIMESTAMP_TAG=${{ env.TIMESTAMP_TAG }}
-          labels: ${{ steps.meta.outputs.labels }}
-          oci: false
-          extra-args: |
-            --target ${{ env.IMAGE_NAME }}
+      - name: Load in podman and tag
+        run: |
+          IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
+          sudo rm -rf ${{ steps.rechunk.outputs.output }}
+          for tag in ${{ steps.generate-tags.outputs.alias_tags }}; do
+            podman tag $IMAGE ${{ env.IMAGE_NAME }}:$tag
+          done
+          # keep for secureboot check TODO
+          # podman tag $IMAGE rechunked-img
 
       # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
       # https://github.com/macbre/push-to-ghcr/issues/12
@@ -163,8 +223,8 @@ jobs:
           REGISTRY_USER: ${{ github.actor }}
           REGISTRY_PASSWORD: ${{ github.token }}
         with:
-          image: ${{ steps.build_image.outputs.image }}
-          tags: ${{ steps.build_image.outputs.tags }}
+          image: ${{ env.IMAGE_NAME }}
+          tags: ${{ steps.generate-tags.outputs.alias_tags }}
           registry: ${{ steps.registry_case.outputs.lowercase }}
           username: ${{ env.REGISTRY_USER }}
           password: ${{ env.REGISTRY_PASSWORD }}
@@ -177,14 +237,11 @@ jobs:
       # to consume. For more details, review the image signing section of the README.
 
       # Sign container
-      - uses: sigstore/cosign-installer@v3.6.0
-        if: github.event_name != 'pull_request'
-
       - name: Sign container image
+        uses: EyeCantCU/cosign-action/sign@v0.3.0
         if: github.event_name != 'pull_request'
-        run: |
-          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.lowercase }}/${{ steps.build_image.outputs.image }}@${TAGS}
-        env:
-          TAGS: ${{ steps.push.outputs.digest }}
-          COSIGN_EXPERIMENTAL: false
-          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
+        with:
+          containers: ${{ env.IMAGE_NAME }}
+          registry-token: ${{ secrets.GITHUB_TOKEN }}
+          signing-secret: ${{ secrets.SIGNING_SECRET }}
+          tags: ${{ steps.push.outputs.outputs && fromJSON(steps.push.outputs.outputs).digest }}
